platform :ios, '9.0'

target 'KaRo' do
  use_frameworks!

  # Pods for KaRo
pod 'SwipeCellKit'
pod 'RealmSwift'
pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
end
